[project]
name = ".github"
revision = "1.0"

[profiles.default]
AWS_ACCESS_KEY_ID = { description = "S3 Access Key", required = true }
AWS_SECRET_ACCESS_KEY = { description = "S3 Secret Key", required = true }
GITHUB_TOKEN = { description = "GitHub token", required = true }
PULUMI_CONFIG_PASSPHRASE = { description = "Pulumi config passphrase", required = true }
